"""forum_redesign_core

Revision ID: e8e80108ea9f
Revises: 
Create Date: 2026-04-20 12:41:42.837724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8e80108ea9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ab_experiments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ab_variant_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('article_embedding_idx'), table_name='articles', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_audit_event_type_created'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_severity_created'), table_name='audit_logs')
    op.drop_index(op.f('uq_ci_feedback'), table_name='content_interactions', postgresql_where="((interaction_type)::text = ANY ((ARRAY['feedback_positive'::character varying, 'feedback_negative'::character varying])::text[]))")
    op.add_column('forum_comments', sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('forum_comments', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_forum_comments_thread_id'), 'forum_comments', ['thread_id'], unique=False)
    op.alter_column('forum_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('forum_threads', sa.Column('vote_up', sa.Integer(), server_default='0', nullable=False))
    op.add_column('forum_threads', sa.Column('vote_down', sa.Integer(), server_default='0', nullable=False))
    op.add_column('forum_threads', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('forum_threads', sa.Column('fact_check_triggered', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('forum_threads', sa.Column('group_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_forum_thread_article'), table_name='forum_threads')
    op.drop_index(op.f('idx_forum_thread_user'), table_name='forum_threads')
    op.drop_index(op.f('idx_forum_thread_category_created'), table_name='forum_threads')
    op.create_index('idx_forum_thread_category_created', 'forum_threads', ['category', 'created_at'], unique=False)
    op.create_index(op.f('ix_forum_threads_article_id'), 'forum_threads', ['article_id'], unique=False)
    op.create_index(op.f('ix_forum_threads_user_id'), 'forum_threads', ['user_id'], unique=False)
    op.alter_column('image_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mf_article_id'), table_name='model_feedback')
    op.drop_index(op.f('idx_mf_user_id'), table_name='model_feedback')
    op.create_index(op.f('ix_model_feedback_article_id'), 'model_feedback', ['article_id'], unique=False)
    op.create_index(op.f('ix_model_feedback_user_id'), 'model_feedback', ['user_id'], unique=False)
    op.drop_index(op.f('news_articles_category_pub_date_idx'), table_name='news_articles')
    op.drop_index(op.f('news_articles_cluster_id_idx'), table_name='news_articles')
    op.drop_index(op.f('news_articles_embedding_idx'), table_name='news_articles', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_news_articles_cluster_id'), 'news_articles', ['cluster_id'], unique=False)
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('follower_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('following_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'follower_count')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_index(op.f('ix_news_articles_cluster_id'), table_name='news_articles')
    op.create_index(op.f('news_articles_embedding_idx'), 'news_articles', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('news_articles_cluster_id_idx'), 'news_articles', ['cluster_id'], unique=False)
    op.create_index(op.f('news_articles_category_pub_date_idx'), 'news_articles', ['category', sa.literal_column('pub_date DESC')], unique=False)
    op.drop_index(op.f('ix_model_feedback_user_id'), table_name='model_feedback')
    op.drop_index(op.f('ix_model_feedback_article_id'), table_name='model_feedback')
    op.create_index(op.f('idx_mf_user_id'), 'model_feedback', ['user_id'], unique=False)
    op.create_index(op.f('idx_mf_article_id'), 'model_feedback', ['article_id'], unique=False)
    op.alter_column('image_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_forum_threads_user_id'), table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_article_id'), table_name='forum_threads')
    op.drop_index('idx_forum_thread_category_created', table_name='forum_threads')
    op.create_index(op.f('idx_forum_thread_category_created'), 'forum_threads', ['category', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_forum_thread_user'), 'forum_threads', ['user_id'], unique=False)
    op.create_index(op.f('idx_forum_thread_article'), 'forum_threads', ['article_id'], unique=False)
    op.drop_column('forum_threads', 'group_id')
    op.drop_column('forum_threads', 'fact_check_triggered')
    op.drop_column('forum_threads', 'view_count')
    op.drop_column('forum_threads', 'vote_down')
    op.drop_column('forum_threads', 'vote_up')
    op.alter_column('forum_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_forum_comments_thread_id'), table_name='forum_comments')
    op.drop_column('forum_comments', 'edited_at')
    op.drop_column('forum_comments', 'is_edited')
    op.create_index(op.f('uq_ci_feedback'), 'content_interactions', ['user_id', 'content_id'], unique=True, postgresql_where="((interaction_type)::text = ANY ((ARRAY['feedback_positive'::character varying, 'feedback_negative'::character varying])::text[]))")
    op.create_index(op.f('idx_audit_severity_created'), 'audit_logs', ['severity', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_event_type_created'), 'audit_logs', ['event_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('article_embedding_idx'), 'articles', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('ab_variant_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ab_experiments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
